// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DryRun(arg1, arg2, arg3) {
  return window['go']['app']['App']['DryRun'](arg1, arg2, arg3);
}

export function GetTools(arg1) {
  return window['go']['app']['App']['GetTools'](arg1);
}

export function ListWorkspace(arg1) {
  return window['go']['app']['App']['ListWorkspace'](arg1);
}

export function OpenWorkspaceFile(arg1) {
  return window['go']['app']['App']['OpenWorkspaceFile'](arg1);
}

export function RunHealthCheck() {
  return window['go']['app']['App']['RunHealthCheck']();
}

export function RunTool(arg1) {
  return window['go']['app']['App']['RunTool'](arg1);
}

export function SetEventEmitter(arg1) {
  return window['go']['app']['App']['SetEventEmitter'](arg1);
}

export function SetPreference(arg1, arg2) {
  return window['go']['app']['App']['SetPreference'](arg1, arg2);
}
