// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DryRun(arg1:string,arg2:string,arg3:string):Promise<model.Decision>;

export function GetTools(arg1:string):Promise<Array<model.Tool>>;

export function ListWorkspace(arg1:string):Promise<Array<model.FileEntry>>;

export function OpenWorkspaceFile(arg1:string):Promise<void>;

export function RunHealthCheck():Promise<Array<model.HealthCheck>>;

export function RunTool(arg1:model.RunRequest):Promise<model.RunResult>;

export function SetEventEmitter(arg1:any):Promise<void>;

export function SetPreference(arg1:string,arg2:string):Promise<void>;
